ProjectoEmplea/apps/ofertas/urls.py
from django.conf.urls import patterns, url

from .views import OfertasCreateView, OfertasListView, OfertaDetailView

urlpatterns = patterns('',
    url(r'^$', OfertasListView.as_view()),
    url(r'^new/jobs/$', OfertasCreateView.as_view(),name='nueva_oferta'),

    url(r'^oferta/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        OfertaDetailView.as_view(), name='listar'),

    url(r'^ajax/$', 'apps.ofertas.views.logic_ajax'),

)

ProjectoEmplea/emplea/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),

    url(r'^ckeditor/', include('ckeditor.urls')),

	url(r'^', include('apps.ofertas.urls', namespace='ofertas')),

)

ProjectoEmplea/apps/ofertas/models.py
import random

from django.db import models
from django.template.defaultfilters import slugify



class CategoriasModel(models.Model):

    nombre = models.CharField(max_length=25)

    def __unicode__(self):
        return self.nombre

def codigo():
    character = ['0','1','2','3','4','5','6','7','8','9',
                'a','b','c','d','e','f','g','h','i','j','k','l','m',
                'n','o','p','q','r','s','t','u','v','w','x','y','z']
    lenCode = 8
    code =''
    i = 0
    while i <= lenCode:
        code += random.choice(character)
        i += 1

    return code

class OfertasModel(models.Model):

    titulo = models.CharField(max_length=50)
    empresa = models.CharField(max_length=25)
    url = models.URLField(null=True, blank=True)
    descripcion = models.TextField()
    lugar = models.CharField(max_length=50)
    comoAplicar = models.TextField()
    publicado = models.DateTimeField(auto_now=True, auto_now_add=True)
    codigo = models.CharField(max_length=9, default=codigo, editable=False)
    slug = models.SlugField(editable=False, unique=False)
    categoria = models.ForeignKey(CategoriasModel)
    activo = models.BooleanField(default=False)


    def __unicode__(self):
        return self.titulo 

    def save(self, *args, **kargs):
        '''Crea el slug de la oferta usando su titulo'''
        if not self.id:
            self.slug = slugify(self.titulo)
        super(OfertasModel, self).save(*args, **kargs)

ProjectoEmplea/apps/ofertas/forms.py
#encoding:utf-8
from django import forms

from captcha.fields import ReCaptchaField
from .models import OfertasModel, codigo

class OfertasForm(forms.ModelForm):
    titulo = forms.CharField(widget=forms.TextInput(attrs={
					'class' : 'large columns',
                    #'placeholder' : 'Se solicita Programador WEB'
            	    }))

    empresa = forms.CharField(widget=forms.TextInput(attrs={
                    'class' : 'large columns',
                    #'placeholder' : 'Nombre de la Empresa'
                    }))

    url = forms.URLField(required=False, widget=forms.TextInput(attrs={
    				'class' : 'small columns',
    				#'placeholder' : 'http://www.tu-empresa.com/'
                    }))

    lugar = forms.CharField(widget=forms.TextInput(attrs={
                    'class' : 'large-12 columns',
                    'placeholder' : 'Santo Domingo / Santiago / La Romana ...'
                     }))

    descripcion = forms.CharField(widget=forms.Textarea(attrs={
                'class':'large-12 columns', 'id' : 'editor'
                }))

    comoAplicar = forms.CharField(widget=forms.Textarea(attrs={
                    'class':'large-12 columns',
                    }))

    codigo = codigo()

    captcha = ReCaptchaField(attrs={'theme':'clean'})

    class Meta:
        model = OfertasModel

ProjectoEmplea/apps/ofertas/views.py
from django.http import HttpResponse, Http404
from django.views.generic import CreateView, ListView, DetailView
from django.core import serializers

from .models import OfertasModel, CategoriasModel
from .forms import OfertasForm


class OfertasCreateView(CreateView):

    form_class = OfertasForm

    template_name = 'ofertas/ofertas_create.html'

    success_url = '/'


class OfertasListView(ListView):

    template_name = 'ofertas/ofertas_list.html'

    context_object_name = 'ofertas'

    #Numero de Ofertas por Pagina
    paginate_by = 10

    def get_queryset(self):
        """ Retorna todas las ofertas en orden inverso
        la 'primera' es la Ultima Oferta publicada """

        return OfertasModel.objects.all()[::-1]

    def get_context_data(self, **kwargs):
        """ para poder listar todas las categorias ( para el filtro ) en el
        mismo template"""
        context = super(OfertasListView, self).get_context_data(**kwargs)
        context['categorias'] = [categoria for categoria in
                                 CategoriasModel.objects.all()]
        return context


class OfertaDetailView(DetailView):

    model = OfertasModel

    template_name = 'ofertas/ofertas_detail.html'

    context_object_name = 'oferta'

    def get_context_data(self, **kwargs):
        context = super(OfertaDetailView, self).get_context_data(**kwargs)
        """ contexto para mostrar las ofertas de la misma categoria de la
        oferta que se esta viendo solo se muestra las ultimas 5"""

        context['similares'] =(
                OfertasModel.objects.filter(
                    categoria=context['object'].categoria).exclude(
                    pk=context['object'].pk)[:5:-1]
            )


        return context


def logic_ajax(request):
    """ Logica para el ajax, solo funciona si es una
        peticion hecha con ajax, de lo contrario
        devuelve un error 404 'pagina no encontrada' """

    if request.is_ajax():
        """ Recogemos el id que nos esta pasando el ajax """
        cat = CategoriasModel.objects.get(id=request.GET['idcategoria'])

        """ Filtramos todas las ofertas que tengan esa categoria """
        ofertas = OfertasModel.objects.filter(categoria=cat)

        """ Ya que ajax no entiende los datos de Python necesitamos
        serializar los datos a JSON para eso se importa los serializers"""
        data = serializers.serialize('json', ofertas,
                                     fields={'pk', 'titulo', 'slug'})

        return HttpResponse(data, content_type='application/json')

    else:
        raise Http404

ProjectoEmplea/templates/base.html
<!doctype html>
<html class="no-js" lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>{% block title %}Emplea{% endblock title %}</title>

    {%load static from staticfiles%}
    <link rel="stylesheet" href="{% static 'css/foundation.css'%}" />
    <link rel="stylesheet" type="text/css" href="{%static 'css/foundation.min.css'%}">
    <script src="{% static 'js/vendor/modernizr.js'%}"></script>
    {% block headscript %}
    {% endblock headscript %}
  </head>
  <body>
    
    <div class="row">
      <div class="large-12 columns panel">
        <h1><a href="/">Emplea.te</a></h1>
      </div>
    </div>


    <div class="row">
        {% block filtro %}

        {% endblock %}


    <div class="large-9 columns">
          {% block content %}

          {% endblock content %}
    </div>
        {% block aside %}

        {% endblock aside %}
    <footer class="row">
        <div class="large-12 columns"><hr/>
            <div class="row panel">
                {% block footer %}
                  <div class="large-6 columns">
                      <p>Ramon Caraballo © 2014-2015.</p>
                  </div>
                {% endblock footer %}
            </div>
        </div>
    </footer>

    </div>


    </div>

    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
  {% block js %}
  {% endblock %}

  </body>
</html>

ProjectoEmplea/templates/ofertas/ofertas_create.html
{% extends "base.html" %}

{% block title %}
	Emplea | Publicar Oferta
{% endblock title %}


{% block content %}
<form method='POST'> {% csrf_token %}
 
  <h3>Info. Sobre la Oferta</h3>
  <hr>

  <h4><strong>Paso 1 </strong>
      <span class='subheader'>Empresa y el Puesto</span></h4>
  <div class="row">
    
    <div class="large-12 columns">
      <label>Titulo:</label>
      {{ form.titulo }}
      {{ form.titulo.errors.as_text }}
    </div>

    <div class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">

      <div class="large-6 columns">
        <label>Empresa
          <span>{{form.empresa}}</span>
          <span>{{form.empresa.errors.as_text}}</span>
        </label>
      </div>

      <div class="large-6 columns">
        <label>URL
          <span>{{form.url}}</span>
          <span>{{form.url.errors.as_text}}</span>
        </label>
      </div>

      <div class="large-6 columns">
        <label>Lugar:
            <span> {{form.lugar}} </span>
            <span> {{form.lugar.errors.as_text}} </span>
        </label>
      </div>

    </div>
    <hr>

    <h3><strong>Paso 2</strong><span class='subheader'> Perfil del
        Puesto</span></h3>

    <div class="row">
      <div class="large-12 columns">
        <label>Descripcion del puesto</label>
          {% load wysiwyg %}
          {% wysiwyg_setup %}
              {{form.descripcion}}
          {% wysiwyg_editor 'editor' %}
          
          {{form.descripcion.errors.as_text}}
      </div>
    </div>
    <br>

    <div class="row">
      <div class="large-6 columns">
        <label>Categoria:
          {{form.categoria}}
        </label>
      </div>
    </div>


    <hr>

    <h3><strong>Paso 3</strong><span class="subheader"> Como
        Aplicar</span></h3>
    <h5 class="subheader">Describe como las personas pueden aplicar a esta oferta</h5>

    <div class="row">
      <div class="large-12 columns">

          {{form.comoAplicar}}
          {{form.comoAplicar.errors.as_text}}

      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">

            {{ form.captcha }}
            {{ form.captcha.errors.as_text }}

      </div>
    </div>
      <input type='submit' value='Publicar' class='button success large-12 columns'>
    </div>
</form>

{% endblock content %}

{% block js %}
<script type="text/javascript">
CKEDITOR.config.toolbar = [

        [ 'Bold','Italic','Underline','Strike','Subscript','-','RemoveFormat', 'NumberedList','BulletedList','-',
            'Outdent','Indent','-','Blockquote','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ],
] ;
</script>
{% endblock %}

ProjectoEmplea/templates/ofertas/ofertas_detail.html
{% extends "base.html" %}

{% block title %}
	OFERTA
{% endblock title %}

{% block content %}

<div class="row">
    <div class="large-12 columns">

        <h2><strong>{{oferta.titulo}}</strong></h2>
        <h4>{{oferta.empresa}}</h4>
        <a href='{{ oferta.url }}'>{{oferta.url}}</a>

        <hr>
        {{oferta.descripcion|safe }}
    </div>

    <div class="large-12 columns">

        <h3 class="subheader">Como aplicar a la oferta</h3>
        <div class="panel">
            <p>{{oferta.comoAplicar}}</p>
        </div>
    </div>

</div>
	
{% endblock content %}

{% block aside %}
    <div class="large-3 columns right">
        <div>
            <h6>Ofertas Similares</h6>
            <hr/>
            {% for similar in similares %}
                <p>
                    <a href="/oferta/{{ similar.slug }}/{{ similar.pk }}">
                    {{ similar.titulo |slice:'10' }}...</a>
                </p>
            {% endfor %}
        </div>

    </div>

{% endblock aside %}

ProjectoEmplea/templates/ofertas/ofertas_list.html
{% extends "base.html" %}}
<!-- -- >
 
{% block title %}

	Emplea.te | Feed

{% endblock title %}

<!-- -- >

{% block filtro%}
    <dl class="sub-nav">
      <dt>Filtrar:</dt>
      <dd class="active cat"><a href="" >ALL</a></dd>
      {%for categoria in categorias %}
      <dd class="cat" id="{{categoria.id}}">
          <a>{{categoria|capfirst}}</a>
      </dd>
      {%endfor%}
    </dl>
{% endblock%}



{% block content %}

        <div id="datosAjax">
            <div class="row" >
                <div class="large-9 columns">

                    {% for oferta in ofertas  %}
                        <h4>
                            <a href='
                            {% url 'ofertas:listar' oferta.slug oferta.pk %}'>
                                <strong>{{oferta.titulo}}</strong>
                            </a>
                        </h4>
                        <p class="subheader">
                            {{oferta.lugar}} @ {{oferta.empresa}}
                        </p>
                        <br/>
                    {% endfor %}
                </div>
            </div>
        </div>

                     {# Crea la paginacion si hay mas de 10 ofertas en esa pag #}

    {% if is_paginated %}


          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="arrow unavailable"><a href="">&laquo;</a></li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
              {% ifequal num page_obj.number %}
                <li class="current disabled"><a href="">{{ num }}</a></li>
              {% else %}
                <li><a href="?page={{ num }}">{{ num }}</a></li>
              {% endifequal %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><a href="">&raquo;</a></li>
            {% endif %}
          </ul>


    {% endif %}
{% endblock content %}


                {# Bloque ASIDE a la DERECHA #}

{%block aside%}
    <aside class="large-3 columns right">
           <div >
               <a class="button success expand " href="
               {% url 'ofertas:nueva_oferta' %}">
                   Publicar Oferta
               </a>
            </div>

        <h5>Buscar</h5>
        <div class="large-12 columns">
            <div class="row collapse">
                <div class="small-10 columns">
                    <input type="text" placeholder="Django">
                </div>
                <div class="small-2 columns">
                    <a href="#" class="button postfix">Go!</a>
                </div>
            </div>
        </div>
      <hr>
        <div class="panel">
            <h5>NOTA</h5>
            <p>El input buscar aun no esta Funcionando</p>
        </div>

    </aside>
{%endblock%}




{% block js %}
<script>
        $('.cat').on('click', clickOnCat);
        function clickOnCat(){
            var cat = $(this).attr('id');

            $('.cat').removeClass('active');

            $(this).addClass('active');

             $.ajax({
                data : {'idcategoria' : cat},
                url : '/ajax/',
                type : 'get',

                success: function (data){
                    var htmlAjax = '';
                    for (var i = 0; i < data.length; i++){
                        htmlAjax += '<div class="row"><div class="large-12 ' +
                                'columns"><a href=" "><strong>'+
                                data[i]
                                .fields["titulo"] +'</strong></a></div></div><hr>';

                    }
                    $('#datosAjax').html(htmlAjax);

                }
            });
        };

</script>
{% endblock %}